name: Create Release

on:
  push:
    # tags:
    #   - "v*"

permissions:
  contents: write

jobs:
  upload-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - name: Build and package server
        run: npm run package -- --targets node18-alpine-x64,node18-linux-x64,node18-macos-x64,node18-win-x64
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: "./builds/handles-server*"
          file_glob: true
          tag: test # TODO: Remove
